services:
    app.mongodb_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments:
            - "@doctrine_mongodb"
        tags:
            - { name: request.param_converter, converter: doctrine.odm }

    app.retrievable_entity_request_body_param_converter:
        parent: fos_rest.converter.request_body
        class: AppBundle\Util\ParamConverter\RetrievableEntityRequestBodyParamConverter
        arguments:
            - "@doctrine_mongodb.odm.document_manager"
            - "@app.retrievable_object_keys_remover"
        tags:
            - { name: request.param_converter, converter: app.retrievable_entity_converter }

    app.retrievable_object_keys_remover:
        class: AppBundle\Util\ParamConverter\RetrievableObjectKeysRemover
        arguments:
            - "@app.fqcn_to_json_key_transformer"

    app.fqcn_to_json_key_transformer:
        class: AppBundle\Util\ParamConverter\FQCNToJsonKeyTransformer
