services:
    app.mongodb_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments:
            - "@doctrine_mongodb"
        tags:
            - { name: request.param_converter, converter: doctrine.odm }

    app.retrievable_entity_request_body_param_converter:
        parent: fos_rest.converter.request_body
        class: AppBundle\Util\ParamConverter\RetrievableEntity\RequestBodyParamConverter
        arguments:
            - "@doctrine_mongodb.odm.document_manager"
            - "@app.retrievable_entity_request_parameters_remover"
            - "@app.retrievable_entity_configuration_factory"
        tags:
            - { name: request.param_converter, converter: app.retrievable_entity_converter }

    app.retrievable_entity_request_parameters_remover:
        class: AppBundle\Util\ParamConverter\RetrievableEntity\RequestParametersRemover

    app.fqcn_to_json_key_transformer:
        class: AppBundle\Util\ParamConverter\RetrievableEntity\FqcnToJsonKeyTransformer

    app.retrievable_entity_configuration_factory:
        class: AppBundle\Util\ParamConverter\RetrievableEntity\ConfigurationFactory
        arguments:
            - "@app.fqcn_to_json_key_transformer"
            - "@app.numeric_to_associative_array_transformer"

    app.numeric_to_associative_array_transformer:
        class: AppBundle\Util\ParamConverter\RetrievableEntity\NumericToAssociativeArrayTransformer
