# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/clients/reminder-engine/webdata/
# For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
#   you can specify a "permissions"
#   section here that describes special permissions to apply to the files
#   in the "files" section as they are being copied over to
#   the Amazon EC2 instance.
#   For more information, see the documentation.
permissions:
  - object: /home/ec2-user/clients/reminder-engine/webdata
    pattern: "**"
    group: www-data
    mode: 2644 # Initial '2' means 'setgid'
    type:
      - file
  - object: /home/ec2-user/clients/reminder-engine/webdata/tools
    pattern: "*.sh"
    mode: 755
    type:
      - file
  - object: /home/ec2-user/clients/reminder-engine/webdata
    pattern: "**"
    except: [var]
    group: www-data
    mode: 6751
    type:
      - directory
  - object: /home/ec2-user/clients/reminder-engine/webdata
    pattern: "var"
    group: www-data
    mode: 6777
    type:
      - directory

hooks:
  AfterInstall:
    - location: deployment_scripts/composer_install.sh
      timeout: 120
    - location: deployment_scripts/cache_clear.sh
      timeout: 120
    - location: deployment_scripts/cache_warmup.sh
      timeout: 120
    - location: deployment_scripts/server_requirements.sh # This needs to come after composer install
      timeout: 120
