# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/clients/reminder-engine/webdata/
# For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
#   you can specify a "permissions"
#   section here that describes special permissions to apply to the files
#   in the "files" section as they are being copied over to
#   the Amazon EC2 instance.
#   For more information, see the documentation.
#permissions:
#  - object:
#    pattern:
#    except:
#    owner:
#    group:
#    mode:
#    acls:
#      -
#    context:
#      user:
#      type:
#      range:
#    type:
#      -
hooks:
  AfterInstall:
    - location: deployment_scripts/composer_install.sh
      timeout: 360

