# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/clients/reminder-engine/webdata/

permissions:
  - object: /home/ec2-user/clients/reminder-engine/webdata
    pattern: "**"
    owner: luqo33 # luqo33 exists both on host and in php-fpm container with UID 1000
    group: www-data
    mode: 644
    type:
      - file
  - object: /home/ec2-user/clients/reminder-engine/webdata
    pattern: "**"
    owner: luqo33
    group: www-data
    mode: 755
  ec2-userec2-user  type:
      - directory

hooks:
  AfterInstall:
    - location: deployment_scripts/composer_install.sh
      timeout: 360
