# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: ltarasiewicz/php71-fpm-alpine-sf-dev:v0.1
  username: $DOCKER_HUB_USER
  password: $DOCKER_HUB_PASSWORD
  email: none

pipelines:
  default:
    - step:
        script:
          - composer install
          - rm -rf vendor/
          - rm -rf web/bundles/
          - rm -rf var/cache/*
          - rm -rf var/sessions/*
          - rm -rf var/logs/*
          - aws deploy push --application-name reminder-engine --s3-location s3://code-deploy-bucket-au/reminder-engine.zip --ignore-hidden-files
          - aws deploy create-deployment --application-name reminder-engine --s3-location bucket=code-deploy-bucket-au,key=reminder-engine.zip,bundleType=zip --deployment-group-name reminder-engine-deployment-group
