# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: 320782110801.dkr.ecr.ap-southeast-2.amazonaws.com/php71-fpm-alpine-sf-dev:v0.1
  username: $AWS_IMAGE_REPOSITORY_USER
  password: $AWS_IMAGE_REPOSITORY_PASSWORD
  email: none

pipelines:
  default:
    - step:
        script:
          - echo hello
          - composer install
          - aws deploy push --application-name reminder-engine --s3-location s3://code-deploy-bucket-au/reminder-engine.zip --ignore-hidden-files
          - aws deploy create-deployment --application-name reminder-engine --s3-location bucket=code-deploy-bucket-au,key=reminder-engine.zip,bundleType=zip --deployment-group-name reminder-engine-deployment-group
