# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ltarasiewicz/php-fpm-alpine-sf-dev:v0.1

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - export IMAGE_NAME=ltarasiewicz/reminder-engine-delpoyment-image:$BITBUCKET_COMMIT
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME .
          # authenticate with the Docker Hub registry
          - docker login --username ltarasiewicz --password Bonzo_86
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME

options:
  docker: true
