version: '2'

services:
  mongodb:
    build: ./mongodb
    image: 320782110801.dkr.ecr.ap-southeast-2.amazonaws.com/mongodb:v0.9
    container_name: mongodb
    env_file:
      - mongodb/mongo-params.env
    ports:
      - "27017:27017"
      - "28017:28017"
  php-fpm-alpine:
    build: ./php-fpm-alpine
    image: 320782110801.dkr.ecr.ap-southeast-2.amazonaws.com/php71-fpm-alpine-sf-dev:v0.2
    container_name: php-reminder-engine
    volumes_from:
      - sourcecode-data
  nginx-alpine: # from alpine:3.4
    build: ./nginx-alpine
    image: 320782110801.dkr.ecr.ap-southeast-2.amazonaws.com/nginx-alpine-wp:v0.7
    ports:
      - "8080:80"
    volumes:
      - re-nginx-logs:/var/log/nginx:rw
    volumes_from:
      - sourcecode-data
  sourcecode-data: # Data-only container
    image: nginx:1.11-alpine
    volumes: # Provide path to your project in the host's filesystem
      - "../.:/var/www/html:rw"

volumes:
  re-nginx-logs:
    external: false
